### ISSUE TITLE
Im CountrySpecificLeaderboard keine Nation anzeigen

### ISSUE THREAD

**Issue by fl0lli** [SoWieMarkus/TrackmaniaCOTDWebsite#1]
// Issue im falschen Repo erstellt.
# Formalien
- [x] Ich habe Code of Conduct gelesen
- [x] Ich habe Terms of Service gelesen
- [x] Es existiert kein Issue zu diesem Thema
- [x] Ich habe das FAQ gelesen
- [x] Ja ich will

# Beschreibung
Die Anzeige einer Nation bei Auswahl ist sinnlos, da ich diese Nation ausgewählt habe.

# Beispiel
- ich wähle auf dem Globus "Deutschland"
- das Leaderboard für Deutschland erscheint
- für jeden Germany-Leaderboard-Entry wird die Nation "Deutschland" (bzw. die Fahne 🇩🇪) angezeigt
- das war mir eigentlich schon klar, weil ich habe ja "Deutschland" ausgewählt

# Reproduzierbarkeit
1. Globus-Seite aufrufen
2. Ein Land auf auswählen
3. Das Country-Specific-Leaderboard anschauen und feststellen, dass für jeden Eintrag die Flagge der gewählten Nation angezeigt wird

# Weitere Anmerkungen
Ich hoffe es ist verständlich,
wenn ich helfen kann lass es mich wissen.

Liebe Grüße
fl0lli

**Comment by fl0lli** [comment]
Ich würde sagen ein possible fix liegt hier:
https://github.com/SoWieMarkus/TrackmaniaCOTDWebsite/blob/e36e8d9a912616b2c66f716768a6308e8895dfad/src/app/leaderboard/leaderboard.component.html#L23-L25

Wenn man eine neuen Parameter für die Leaderboard-Component hinzufügt, der angibt ob die Nation angezeigt werden soll (Default true):

``` typescript
export class LeaderboardComponent implements OnInit {

  @Input() leaderboard!: Leaderboard;

  @Input() showNation: boolean = true;

}
```
``` typescript
<td *ngIf="showNation"> 
    <app-flag [zone]="player.zone"></app-flag> 
</td> 
```

Dann muss man nur noch wie gehabt den Parameter in dem CountrySpecificLeadboard übergeben:
``` typescript
<app-leaderboard [leaderboard]="leaderboard" [showNation]="false"></app-leaderboard>
```

**Comment by SoWieMarkus** [comment]
![bust_flolli_issue](https://user-images.githubusercontent.com/44964229/152663111-2e7882fa-9a4f-4f2b-8b9c-0bf74601b90f.png)

**Comment by SoWieMarkus** [comment]
Will not be implemented because of the Inselaffen.
lg

**Comment by fl0lli** [comment]
fixed it
```
<td *ngIf="showNation || player.zone.equals(Zone.Inselaffen)"> 
    <app-flag [zone]="player.zone"></app-flag> 
</td> 
```

gotta hate those inseläffs
